# PyTorch basics
PyTorch is a Python library that includes several functionalities to simplify the programming and training of neural networks. It also includes a simple way of performing the calculations required for the training process in a CUDA GPU (Nvidia) if available, making the process considerably faster than in a CPU.

PyTorch tensors are very similar to NumPy arrays, but they include additional features to simplify the definition of your neural network and perform calculations in a GPU. Let us see some basic tensor definitions. First, we have to import the **torch** package

In [1]:
import torch
import numpy as np

Now we can define a tensor with random values (between 0 and 1). We will make one of dimensions 6

In [2]:
x = torch.rand(6)
print(x)

tensor([0.6033, 0.8453, 0.1997, 0.7797, 0.2916, 0.4091])


We can reshape this tensor by using the **view()** function

In [3]:
x = x.view(2,3)
print(x)

tensor([[0.6033, 0.8453, 0.1997],
        [0.7797, 0.2916, 0.4091]])


The elements of a tensor can be obtained the same way as with NumPy arrays

In [4]:
print(x[0,0])
print(x[:,0])

tensor(0.6033)
tensor([0.6033, 0.7797])


The dimensions of the tensor can be obtained by using the **size()** function

In [5]:
print(x.size())

torch.Size([2, 3])


Similar to NumPy, PyTorch includes functions to create tensors with all the elements equal to 0 or 1

In [6]:
print(torch.ones(3,3))
print(torch.zeros(3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


We can change between tensors and arrays easily by using **numpy()** and **torch.from_numpy()**

In [7]:
x = x.numpy()
print(x)
x = torch.from_numpy(x)
print(x)

[[0.60331374 0.8453349  0.19972092]
 [0.7797336  0.29161322 0.40914375]]
tensor([[0.6033, 0.8453, 0.1997],
        [0.7797, 0.2916, 0.4091]])


Finally, we can send this tensors to the GPU. This step is optional, since the calculations can be performed in the CPU, although using a GPU will make the training process faster. In order to do this, we first try to obtain the GPU

In [8]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


If we have installed PyTorch with CUDA and we have a compatible GPU, we should have obtained that device is cuda. Now, in order to send the tensors to the GPU, we just have to use the **to()** function. We can check if the tensor has been sent correctly to the GPU with **is_cuda**

In [9]:
x.to(device)
print(x.is_cuda)

False
